#!/usr/bin/env python

def countToFour1():
    for eachNum in range(5):
        print eachNum,

def countToFour2(n):
    for eachNum in range(n,5):
        print eachNum,

def countToFour3(n=1):
    for eachNum in range(n,5):
        print eachNum,

a=countToFour1
b=countToFour2
c=countToFour3
#a(2)
#a(4)
#a(5)
a()
b(2)
b(4)
b(5)
b()
c(2)
c(4)
c(5)
c()
